### ISSUE TITLE
Following the "Client (application) flow" in `README.md` returns `unknown keyword: :client_secret`

### ISSUE THREAD

**Issue by synthead** [mauricew/ruby-twitch-api#66] opened 2021-11-29 04:58 UTC
[The "Client (application) flow" section of `README.md`](https://github.com/mauricew/ruby-twitch-api#client-application-flow) states:

> 
> #### Client (application) flow
> 
> This is default flow (`:token_type`).
> 
> ```ruby
> twitch_client = Twitch::Client.new(
>   client_id: client_id,
>   client_secret: client_secret,
> 
>   ## this is default
>   # token_type: :application,
> 
>   ## this can be required by some Twitch end-points
>   # scopes: scopes,
> 
>   ## if you already have one
>   # access_token: access_token
> )
> ```

However, this code...

```ruby
require "twitch-api"

CLIENT_ID = "hackme"
CLIENT_SECRET = "hackme"

twitch_client = Twitch::Client.new(
  client_id: CLIENT_ID,
  client_secret: CLIENT_SECRET
)
```

...returns:

```
/home/max/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/twitch-api-0.4.0/lib/twitch/client.rb:32:in `initialize': unknown keyword: :client_secret (ArgumentError)
	from ./check:9:in `new'
	from ./check:9:in `<main>'
```

Is there something I'm doing wrong?

**Comment by synthead** [comment] 2021-11-29 05:03
Ah, it looks like the last time this gem was updated was three years ago.  That was when 0.4.0 was released.

The `README.md` has different documentation for this very old version: https://github.com/mauricew/ruby-twitch-api/tree/v0.4.0

Is there a chance we could see a new gem added to rubygems.org?

**Comment by AlexWayfer** [comment] 2023-07-25 16:15
> Is there a chance we could see a new gem added to rubygems.org?

Yeah, there is a chance: I'm a collaborator of this repo, and I hope we'll setup me as maintainer of the gem on RubyGems.org: https://github.com/mauricew/ruby-twitch-api/issues/29#issuecomment-1536195903

Let's wait for little actions by @mauricew and leave him alone, to deal with his real-life problems. I hope I'll be able to continue the life of this gem.

---

So, if there is only a question about new release — can we close it as a duplicate of #29?

**Comment by synthead** [comment] 2023-08-08 17:04
If it helps, I like to link the gem homepage to a tagged release, like so:

https://github.com/synthead/timex_datalink_client/blob/0e2117314f31272d0b32ebb6597d1e4589147c1c/timex_datalink_client.gemspec#L11

```ruby
  s.homepage    = "https://github.com/synthead/timex_datalink_client/tree/v#{s.version}"
```

This way, [from rubygems.org](https://rubygems.org/gems/timex_datalink_client), the homepage link will direct the user to the version released in the gem.  When they read the documentation, the version of the gem and the documentation that was shipped with it will line up :+1:

**Comment by AlexWayfer** [comment] 2023-08-08 17:36
> If it helps, I like to link the gem homepage to a tagged release, like so:
> 
> https://github.com/synthead/timex_datalink_client/blob/0e2117314f31272d0b32ebb6597d1e4589147c1c/timex_datalink_client.gemspec#L11
> 
> ```ruby
>   s.homepage    = "https://github.com/synthead/timex_datalink_client/tree/v#{s.version}"
> ```
> 
> This way, [from rubygems.org](https://rubygems.org/gems/timex_datalink_client), the homepage link will direct the user to the version released in the gem. When they read the documentation, the version of the gem and the documentation that was shipped with it will line up 👍

Good note, thank you. I know about this approach, and support it. For example, it's even in my gem template: https://github.com/AlexWayfer/gem_template/blob/31fd287/template/gem_name.gemspec.erb#L24

I'll reopen this issue as a reminder to do so for this gem.

**Comment by AlexWayfer** [comment] 2023-08-08 17:40
Oh, you're talking about homepage link, not documentation.

Hm, then it's doubtful.

Although GitHub (surprisingly) displays normal page for a link as you provided, I mean with tabs like issues and other stuff. I thought it'd be just files tree and it's not appropriate as a homepage link.

I'll think about it.

BTW, if you're looking for documentation — click "Documentation" link. 😉 It's already correct, as I see.

**Comment by AlexWayfer** [comment] 2023-08-08 17:43
I've compared two links, with and without tag, and have found out that there is no notice about outdating version of displayed content. Like in forks, for example. So no, I'm against version tag in the homepage link.

GitHub repository is our home. And if you want to watch at it — you'll receive the current version of content (instead of thinking "oh, so old commits, no activity, bye"). But if you want to check the documentation — you should click "Documentation" link, as I wrote. Or even check out the README file in the installed gem directory, possible in offline.

**Closed by AlexWayfer** 2023-08-08 17:43 UTC
